IF OBJECT_ID('dbo.HUB_CUSTOMER', 'U') IS NOT NULL DROP TABLE dbo.HUB_CUSTOMER
IF OBJECT_ID('dbo.HUB_INCENTIVE_OFFER', 'U') IS NOT NULL DROP TABLE dbo.HUB_INCENTIVE_OFFER
IF OBJECT_ID('dbo.HUB_MEMBERSHIP_PLAN', 'U') IS NOT NULL DROP TABLE dbo.HUB_MEMBERSHIP_PLAN
IF OBJECT_ID('dbo.HUB_SEGMENT', 'U') IS NOT NULL DROP TABLE dbo.HUB_SEGMENT
IF OBJECT_ID('dbo.LNK_CUSTOMER_COSTING', 'U') IS NOT NULL DROP TABLE dbo.LNK_CUSTOMER_COSTING
IF OBJECT_ID('dbo.LNK_CUSTOMER_OFFER', 'U') IS NOT NULL DROP TABLE dbo.LNK_CUSTOMER_OFFER
IF OBJECT_ID('dbo.LNK_MEMBERSHIP', 'U') IS NOT NULL DROP TABLE dbo.LNK_MEMBERSHIP
IF OBJECT_ID('dbo.LNK_RENEWAL_MEMBERSHIP', 'U') IS NOT NULL DROP TABLE dbo.LNK_RENEWAL_MEMBERSHIP
IF OBJECT_ID('dbo.LSAT_CUSTOMER_COSTING', 'U') IS NOT NULL DROP TABLE dbo.LSAT_CUSTOMER_COSTING
IF OBJECT_ID('dbo.LSAT_CUSTOMER_OFFER', 'U') IS NOT NULL DROP TABLE dbo.LSAT_CUSTOMER_OFFER
IF OBJECT_ID('dbo.LSAT_MEMBERSHIP', 'U') IS NOT NULL DROP TABLE dbo.LSAT_MEMBERSHIP
IF OBJECT_ID('dbo.SAT_CUSTOMER', 'U') IS NOT NULL DROP TABLE dbo.SAT_CUSTOMER
IF OBJECT_ID('dbo.SAT_CUSTOMER_ADDITIONAL_DETAILS', 'U') IS NOT NULL DROP TABLE dbo.SAT_CUSTOMER_ADDITIONAL_DETAILS
IF OBJECT_ID('dbo.SAT_INCENTIVE_OFFER', 'U') IS NOT NULL DROP TABLE dbo.SAT_INCENTIVE_OFFER
IF OBJECT_ID('dbo.SAT_MEMBERSHIP_PLAN_DETAIL', 'U') IS NOT NULL DROP TABLE dbo.SAT_MEMBERSHIP_PLAN_DETAIL
IF OBJECT_ID('dbo.SAT_MEMBERSHIP_PLAN_VALUATION', 'U') IS NOT NULL DROP TABLE dbo.SAT_MEMBERSHIP_PLAN_VALUATION
IF OBJECT_ID('dbo.SAT_SEGMENT', 'U') IS NOT NULL DROP TABLE dbo.SAT_SEGMENT
IF OBJECT_ID('dbo.BR_MEMBERSHIP_OFFER', 'U') IS NOT NULL DROP TABLE dbo.BR_MEMBERSHIP_OFFER
IF OBJECT_ID('dbo.SAT_BDV_CUSTOMER_DERIVED', 'U') IS NOT NULL DROP TABLE dbo.SAT_BDV_CUSTOMER_DERIVED
IF OBJECT_ID('bdv.vw_CUSTOMER_DERIVED', 'U') IS NOT NULL DROP TABLE dbo.SAT_BDV_CUSTOMER_DERIVED

-- HUB CUSTOMER
CREATE TABLE dbo.HUB_CUSTOMER
(
  [CUSTOMER_SK] binary(16) NOT NULL,
  [AUDIT_TRAIL_ID] integer NOT NULL,
  [INSCRIPTION_TIMESTAMP] datetime2(7) NOT NULL,
  [CUSTOMER_ID] nvarchar(100) NOT NULL,
  CONSTRAINT [PK_HUB_CUSTOMER] PRIMARY KEY NONCLUSTERED ([CUSTOMER_SK] ASC)
)

CREATE UNIQUE CLUSTERED INDEX IX_HUB_CUSTOMER ON dbo.HUB_CUSTOMER
(
  [CUSTOMER_ID] ASC
)

-- HUB INCENTIVE OFFER
CREATE TABLE dbo.HUB_INCENTIVE_OFFER
(
  [INCENTIVE_OFFER_SK] binary(16) NOT NULL,
  [AUDIT_TRAIL_ID] integer NOT NULL,
  [INSCRIPTION_TIMESTAMP] datetime2(7) NOT NULL,
  [OFFER_ID] nvarchar(100) NOT NULL,
  CONSTRAINT [PK_HUB_INCENTIVE_OFFER] PRIMARY KEY NONCLUSTERED ([INCENTIVE_OFFER_SK] ASC)
)

CREATE UNIQUE CLUSTERED INDEX IX_HUB_INCENTIVE_OFFER ON dbo.HUB_INCENTIVE_OFFER
(
    [OFFER_ID] ASC
)

-- HUB MEMBERSHIP PLAN
CREATE TABLE dbo.HUB_MEMBERSHIP_PLAN
(
  [MEMBERSHIP_PLAN_SK] binary(16) NOT NULL,
  [AUDIT_TRAIL_ID] integer NOT NULL,
  [INSCRIPTION_TIMESTAMP] datetime2(7) NOT NULL,
  [PLAN_CODE] nvarchar(100) NOT NULL,
  [PLAN_SUFFIX] nvarchar(100) NOT NULL,
  CONSTRAINT [PK_HUB_MEMBERSHIP_PLAN] PRIMARY KEY NONCLUSTERED ([MEMBERSHIP_PLAN_SK] ASC)
)

CREATE UNIQUE CLUSTERED INDEX IX_HUB_MEMBERSHIP_PLAN ON dbo.HUB_MEMBERSHIP_PLAN
(
  PLAN_CODE ASC,
  PLAN_SUFFIX ASC
)

-- HUB SEGMENT
CREATE TABLE dbo.HUB_SEGMENT
(
  [SEGMENT_SK] binary(16) NOT NULL,
  [AUDIT_TRAIL_ID] integer NOT NULL,
  [INSCRIPTION_TIMESTAMP] datetime2(7) NOT NULL,
  [SEGMENT_CODE] nvarchar(100) NOT NULL,
  CONSTRAINT [PK_HUB_SEGMENT] PRIMARY KEY NONCLUSTERED (SEGMENT_SK ASC)
)

CREATE UNIQUE CLUSTERED INDEX IX_HUB_SEGMENT ON dbo.HUB_SEGMENT
(
  [SEGMENT_CODE] ASC
)

-- LNK CUSTOMER COSTING
CREATE TABLE dbo.LNK_CUSTOMER_COSTING
(
  [CUSTOMER_COSTING_SK] binary(16) NOT NULL,
  [AUDIT_TRAIL_ID] integer NOT NULL,
  [[INSCRIPTION_TIMESTAMP] datetime2(7) NOT NULL,
  [MEMBERSHIP_PLAN_SK] binary(16) NOT NULL,
  [CUSTOMER_SK] binary(16) NOT NULL,
  [SEGMENT_SK] binary(16) NOT NULL,
  CONSTRAINT [PK_LNK_CUSTOMER_COSTING] PRIMARY KEY NONCLUSTERED ([CUSTOMER_COSTING_SK] ASC)
)

CREATE UNIQUE CLUSTERED INDEX IX_LNK_CUSTOMER_COSTING ON dbo.LNK_CUSTOMER_COSTING
(
  CUSTOMER_SK ASC,
  MEMBERSHIP_PLAN_SK ASC,
  SEGMENT_SK ASC
)

-- LNK CUSTOMER OFFER
CREATE TABLE dbo.LNK_CUSTOMER_OFFER
(
  [CUSTOMER_OFFER_SK] binary(16) NOT NULL,
  [AUDIT_TRAIL_ID] integer NOT NULL,
  [[INSCRIPTION_TIMESTAMP] datetime2(7) NOT NULL,
  [CUSTOMER_SK] binary(16) NOT NULL,
  [INCENTIVE_OFFER_SK] binary(16) NOT NULL,
  CONSTRAINT [PK_LNK_CUSTOMER_OFFER] PRIMARY KEY NONCLUSTERED([CUSTOMER_OFFER_SK] ASC)
)

CREATE UNIQUE CLUSTERED INDEX IX_LNK_CUSTOMER_OFFER ON dbo.LNK_CUSTOMER_OFFER
(
  [CUSTOMER_SK] ASC,
  [INCENTIVE_OFFER_SK] ASC
)

EXEC sp_addextendedproperty
@name = 'Driving_Key_Indicator', @value = 'True',
@level0type = 'SCHEMA', @level0name = 'dbo',
@level1type = 'TABLE', @level1name = 'LNK_CUSTOMER_OFFER',
@level2type = 'COLUMN', @level2name = 'CUSTOMER_SK'

-- LNK MEMBERSHIP
CREATE TABLE dbo.LNK_MEMBERSHIP
(
  [MEMBERSHIP_SK] binary(16) NOT NULL,
  [AUDIT_TRAIL_ID] integer NOT NULL,
  [INSCRIPTION_TIMESTAMP] datetime2(7) NOT NULL,
  [CUSTOMER_SK] binary(16) NOT NULL,
  [MEMBERSHIP_PLAN_SK] binary(16) NOT NULL,
  [SALES_CHANNEL] nvarchar(100) NOT NULL,
  CONSTRAINT [PK_LNK_MEMBERSHIP] PRIMARY KEY NONCLUSTERED(MEMBERSHIP_SK ASC)
)

CREATE UNIQUE CLUSTERED INDEX IX_LNK_MEMBERSHIP ON dbo.LNK_MEMBERSHIP
(
  [CUSTOMER_SK] ASC,
  [MEMBERSHIP_PLAN_SK] ASC,
  [SALES_CHANNEL] ASC
)

-- LNK RENEWAL_MEMBERSHIP
CREATE TABLE[dbo].[LNK_RENEWAL_MEMBERSHIP]
(
  [RENEWAL_MEMBERSHIP_SK][binary](16) NOT NULL,
  [AUDIT_TRAIL_ID] integer NOT NULL,
  [INSCRIPTION_TIMESTAMP] datetime2(7) NOT NULL,
  [MEMBERSHIP_PLAN_SK] [binary] (16) NOT NULL,
  [RENEWAL_PLAN_SK] [binary] (16) NOT NULL,
  CONSTRAINT [PK_LNK_RENEWAL_MEMBERSHIP] PRIMARY KEY NONCLUSTERED ([RENEWAL_MEMBERSHIP_SK] ASC)
) ON [PRIMARY]

CREATE UNIQUE CLUSTERED INDEX IX_LNK_RENEWAL_MEMBERSHIP ON dbo.LNK_RENEWAL_MEMBERSHIP
(
  [MEMBERSHIP_PLAN_SK] ASC,
  [RENEWAL_PLAN_SK] ASC
)

-- LSAT CUSTOMER COSTING
CREATE TABLE dbo.LSAT_CUSTOMER_COSTING
(
  [CUSTOMER_COSTING_SK] binary(16) NOT NULL,
  [COSTING_EFFECTIVE_DATE] datetime2(7) NOT NULL,
  [INSCRIPTION_TIMESTAMP] datetime2(7) NOT NULL,
  [AUDIT_TRAIL_ID] integer NOT NULL,
  [CHANGE_DATA_INDICATOR] varchar(100) NOT NULL,
  [INSCRIPTION_RECORD_ID] integer NOT NULL,
  [CHECKSUM] binary(16) NOT NULL,
  [PERSONAL_MONTHLY_COST] numeric(38,20) NULL,
  CONSTRAINT [PK_LSAT_CUSTOMER_COSTING] PRIMARY KEY CLUSTERED (CUSTOMER_COSTING_SK ASC, [INSCRIPTION_TIMESTAMP] ASC, [INSCRIPTION_RECORD_ID] ASC, COSTING_EFFECTIVE_DATE ASC)
)

-- LSAT CUSTOMER OFFER
CREATE TABLE dbo.LSAT_CUSTOMER_OFFER
(
  [CUSTOMER_OFFER_SK] binary(16) NOT NULL,
  [INSCRIPTION_TIMESTAMP] datetime2(7) NOT NULL,
  [AUDIT_TRAIL_ID] integer NOT NULL,
  [CHANGE_DATA_INDICATOR] varchar(100) NOT NULL,
  [INSCRIPTION_RECORD_ID] integer NOT NULL,
  [CHECKSUM] binary(16) NOT NULL,
  CONSTRAINT [PK_LSAT_CUSTOMER_OFFER] PRIMARY KEY CLUSTERED (CUSTOMER_OFFER_SK ASC, [INSCRIPTION_TIMESTAMP] ASC, [INSCRIPTION_RECORD_ID] ASC)
)

-- LSAT MEMBERSHIP
CREATE TABLE dbo.LSAT_MEMBERSHIP
(
  [MEMBERSHIP_SK] binary(16) NOT NULL,
  [INSCRIPTION_TIMESTAMP] datetime2(7) NOT NULL,
  [AUDIT_TRAIL_ID] integer NOT NULL,
  [CHANGE_DATA_INDICATOR] varchar(100) NOT NULL,
  [INSCRIPTION_RECORD_ID] integer NOT NULL,
  [CHECKSUM] binary(16) NOT NULL,
  [MEMBERSHIP_START_DATE] datetime2(7) NULL,
  [MEMBERSHIP_END_DATE] datetime2(7) NULL,
  [MEMBERSHIP_STATUS] nvarchar(100) NULL,
  CONSTRAINT [PK_LSAT_MEMBERSHIP] PRIMARY KEY CLUSTERED (MEMBERSHIP_SK ASC, [INSCRIPTION_TIMESTAMP] ASC, [INSCRIPTION_RECORD_ID] ASC)
)

-- SAT CUSTOMER
CREATE TABLE dbo.SAT_CUSTOMER
(
  [CUSTOMER_SK] binary(16) NOT NULL,
  [INSCRIPTION_TIMESTAMP] datetime2(7) NOT NULL,
  [AUDIT_TRAIL_ID] integer NOT NULL,
  [CHANGE_DATA_INDICATOR] varchar(100) NOT NULL,
  [INSCRIPTION_RECORD_ID] integer NOT NULL,
  [CHECKSUM] binary(16) NOT NULL,
  [GIVEN_NAME] nvarchar(100) NULL,
  [SURNAME] nvarchar(100) NULL,
  [SUBURB] nvarchar(100) NULL,
  [POSTCODE] nvarchar(100) NULL,
  [COUNTRY] nvarchar(100) NULL,
  [GENDER] nvarchar(100) NULL,
  [DATE_OF_BIRTH] datetime2(7) NULL,
  [VALID_FROM] datetime2(7) NULL,
  [REFERRAL_OFFER_MADE_INDICATOR] nvarchar(100) NULL,
  CONSTRAINT [PK_SAT_CUSTOMER] PRIMARY KEY CLUSTERED (CUSTOMER_SK ASC, [INSCRIPTION_TIMESTAMP] ASC, [INSCRIPTION_RECORD_ID] ASC)
)

-- SAT CUSTOMER ADDITIONAL DETAILS
CREATE TABLE dbo.SAT_CUSTOMER_ADDITIONAL_DETAILS
(
  [CUSTOMER_SK] binary(16) NOT NULL,
  [INSCRIPTION_TIMESTAMP] datetime2(7) NOT NULL,
  [AUDIT_TRAIL_ID] integer NOT NULL,
  [CHANGE_DATA_INDICATOR] varchar(100) NOT NULL,
  [INSCRIPTION_RECORD_ID] integer NOT NULL,
  [CHECKSUM] binary(16) NOT NULL,
  [CONTACT_NUMBER] nvarchar(100) NULL,
  [STATE] nvarchar(100) NULL,
  CONSTRAINT [PK_SAT_CUSTOMER_ADDITIONAL_DETAILS] PRIMARY KEY CLUSTERED (CUSTOMER_SK ASC, [INSCRIPTION_TIMESTAMP] ASC, [INSCRIPTION_RECORD_ID] ASC)
)

-- SAT INCENTIVE OFFER
CREATE TABLE dbo.SAT_INCENTIVE_OFFER
(
  [INCENTIVE_OFFER_SK] binary(16) NOT NULL,
  [INSCRIPTION_TIMESTAMP] datetime2(7) NOT NULL,
  [AUDIT_TRAIL_ID] integer NOT NULL,
  [CHANGE_DATA_INDICATOR] varchar(100) NOT NULL,
  [INSCRIPTION_RECORD_ID] integer NOT NULL,
  [CHECKSUM] binary(16) NOT NULL,
  [OFFER_DESCRIPTION] nvarchar(100) NULL,
  CONSTRAINT [PK_SAT_INCENTIVE_OFFER] PRIMARY KEY CLUSTERED(INCENTIVE_OFFER_SK ASC, [INSCRIPTION_TIMESTAMP] ASC, [INSCRIPTION_RECORD_ID] ASC)
)

-- SAT MEMBERSHIP PLAN DETAIL
CREATE TABLE dbo.SAT_MEMBERSHIP_PLAN_DETAIL
(
  [MEMBERSHIP_PLAN_SK] binary(16) NOT NULL,
  [[INSCRIPTION_TIMESTAMP] datetime2(7) NOT NULL,
  [AUDIT_TRAIL_ID] integer NOT NULL,
  [CHANGE_DATA_INDICATOR] varchar(100) NOT NULL,
  [INSCRIPTION_RECORD_ID] integer NOT NULL,
  [CHECKSUM] binary(16) NOT NULL,
  [PLAN_DESCRIPTION] nvarchar(100) NULL,
  CONSTRAINT [PK_SAT_MEMBERSHIP_PLAN_DETAIL] PRIMARY KEY CLUSTERED(MEMBERSHIP_PLAN_SK ASC, [INSCRIPTION_TIMESTAMP] ASC, [INSCRIPTION_RECORD_ID] ASC)
)

-- SAT MEMBERSHIP PLAN VALUATION
CREATE TABLE dbo.SAT_MEMBERSHIP_PLAN_VALUATION
(
  [MEMBERSHIP_PLAN_SK] binary(16) NOT NULL,
  [PLAN_VALUATION_DATE] datetime2(7) NOT NULL,
  [[INSCRIPTION_TIMESTAMP] datetime2(7) NOT NULL,
  [AUDIT_TRAIL_ID] integer NOT NULL,
  [CHANGE_DATA_INDICATOR] varchar(100) NOT NULL,
  [INSCRIPTION_RECORD_ID] integer NOT NULL,
  [CHECKSUM] binary(16) NOT NULL,
  [PLAN_VALUATION_AMOUNT] numeric(38,20) NULL,
  CONSTRAINT [PK_SAT_MEMBERSHIP_PLAN_VALUATION] PRIMARY KEY CLUSTERED(MEMBERSHIP_PLAN_SK ASC, [INSCRIPTION_TIMESTAMP] ASC, [INSCRIPTION_RECORD_ID] ASC, PLAN_VALUATION_DATE ASC)
)

-- SAT SEGMENT
CREATE TABLE dbo.SAT_SEGMENT
(
  [SEGMENT_SK ]binary(16) NOT NULL,
  [INSCRIPTION_TIMESTAMP] datetime2(7) NOT NULL,
  [AUDIT_TRAIL_ID] integer NOT NULL,
  [CHANGE_DATA_INDICATOR] varchar(100) NOT NULL,
  [INSCRIPTION_RECORD_ID] integer NOT NULL,
  [CHECKSUM] binary(16) NOT NULL,
  [SEGMENT_DESCRIPTION] nvarchar(100) NULL,
  CONSTRAINT [PK_SAT_SEGMENT] PRIMARY KEY CLUSTERED (SEGMENT_SK ASC, [INSCRIPTION_TIMESTAMP] ASC, [INSCRIPTION_RECORD_ID] ASC)
)

-- BR MEMBERSHIP OFFER
CREATE TABLE[dbo].[BR_MEMBERSHIP_OFFER]
(
  [SNAPSHOT_DATETIME][datetime2](7) NOT NULL,
  [CUSTOMER_OFFER_SK] binary(16) NOT NULL,
  [MEMBERSHIP_SK] binary(16) NOT NULL,
  [CUSTOMER_SK] binary(16) NOT NULL,
  [MEMBERSHIP_PLAN_SK] binary(16) NOT NULL,
  [SALES_CHANNEL] [nvarchar] (100) NOT NULL,
  CONSTRAINT [PK_BR_MEMBERSHIP_OFFER] PRIMARY KEY CLUSTERED([SNAPSHOT_DATETIME] ASC, [CUSTOMER_OFFER_SK] ASC, [MEMBERSHIP_SK] ASC, [CUSTOMER_SK] ASC, [MEMBERSHIP_PLAN_SK] ASC, [SALES_CHANNEL] ASC)
) ON [PRIMARY]

-- BDV table
CREATE TABLE [dbo].[SAT_BDV_CUSTOMER_DERIVED](
	[CUSTOMER_SK] [binary](16) NOT NULL,
	[INSCRIPTION_TIMESTAMP] [datetime2](7) NOT NULL,
	[AUDIT_TRAIL_ID] [int] NOT NULL,
	[CHANGE_DATA_INDICATOR] [varchar](100) NOT NULL,
	[INSCRIPTION_RECORD_ID] [int] NOT NULL,
	[CHECKSUM] [binary](16) NOT NULL,
	[REFERRAL_OFFER_CLEAN] [nvarchar](100) NULL,
 CONSTRAINT [PK_SAT_CUSTOMER_DERIVED] PRIMARY KEY CLUSTERED 
(
	[CUSTOMER_HSH] ASC,
	[INSCRIPTION_TIMESTAMP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'bdv')
BEGIN
EXEC('CREATE SCHEMA bdv')
END
GO

-- BDV (source) view
CREATE OR ALTER VIEW [bdv].[vw_CUSTOMER_DERIVED] AS
SELECT b.CUSTOMER_ID
      ,a.[INSCRIPTION_TIMESTAMP]
	  ,a.[INSCRIPTION_TIMESTAMP] AS [STATE_TIMESTAMP]
      ,a.[CHANGE_DATA_INDICATOR]
      ,a.[INSCRIPTION_RECORD_ID]
      ,a.[RECORD_SOURCE_INDICATOR]
      ,CASE [REFERRAL_OFFER_MADE_INDICATOR]
		WHEN '1'	THEN 'True'
		WHEN '0'	THEN 'False'
		ELSE 'Unknown'
	  END AS REFERRAL_OFFER_CLEAN
FROM [SAT_CUSTOMER] a
JOIN [HUB_CUSTOMER] b ON a.CUSTOMER_SK = b.CUSTOMER_SK