CREATE OR ALTER VIEW [bdv].[vw_CUSTOMER_DERIVED] AS
SELECT b.CUSTOMER_ID
      ,a.[INSCRIPTION_TIMESTAMP]
	  ,a.[STATE_TIMESTAMP] AS [SOURCE_TIMESTAMP]
      --,a.[LOAD_END_DATETIME]
      --,a.[CURRENT_RECORD_INDICATOR]
      --,a.[ETL_INSERT_RUN_ID]
      --,[ETL_UPDATE_RUN_ID]
      ,a.[CHANGE_DATA_INDICATOR]
      ,a.[INSCRIPTION_RECORD_ID]
      ,CASE [REFERRAL_OFFER_MADE_INDICATOR]
		WHEN '1'	THEN 'True'
		WHEN '0'	THEN 'False'
		ELSE 'Unknown'
	  END AS REFERRAL_OFFER_CLEAN
FROM dbo.[SAT_CUSTOMER] a
JOIN dbo.[HUB_CUSTOMER] b ON a.CUSTOMER_SK = b.CUSTOMER_SK